"""Pipeline: {{ cookiecutter.pipeline_name }}

Generated by SynaFlow scaffold template.
"""
from collections.abc import Generator, Iterator
from typing import NamedTuple

from synaflow import PipelineRegistry, pipeline, run, step


class Params(NamedTuple):
    count: int = 10


def producer(count: int) -> Generator[int, None, None]:
    """Produces a stream of integers."""
    yield from range(count)


def transformer(producer: int) -> int:
    """Transforms each item (EACH mode)."""
    return producer * 2


def consumer(transformer: Iterator[int]) -> None:
    """Consumes the transformed stream."""
    for x in transformer:
        print(x)


# Design-time: the catalog is built at module load. ``catalog.get_dag(name)``
# compiles the Dag on first call and caches it for subsequent runs.
catalog = PipelineRegistry()
catalog["{{ cookiecutter.pipeline_name }}"] = pipeline(
    name="{{ cookiecutter.pipeline_name }}",
    params=Params,
    steps=[
        step("producer", fn=producer),
        step("transformer", fn=transformer),
        step("consumer", fn=consumer),
    ],
)


def main():
    # Runtime: consume the prebuilt Dag, never recompile.
    run(catalog.get_dag("{{ cookiecutter.pipeline_name }}"), Params(count=5))


if __name__ == "__main__":
    main()
